CREATE DATABASE EXPENSES;
 CREATE TABLE UsersTable 
    (
        u_id SERIAL VARCHAR(100) FOREIGN KEY PRIMARY KEY UNIQUE,
        email VARCHAR(255) NOT NULL UNIQUE,
        store BOOLEAN,
        joined_at TIMESTAMP NOt NULL
    )
 